// lib/quizContentDA.js
//
// Danish mirror of the learningModules / learningSteps FALLBACK arrays in
// pages/portal.js. Same Module IDs, Step Numbers, icons, colors, URLs, and
// Active flags as the English version — only the human-facing text
// (Subject, Class, Title, Introduction, Now You Try, Learning Section,
// Teaching, Question, Option A-D, Explanation, Learn More Label) differs.
//
// IMPORTANT — 'English Grammar' subject is intentionally NOT translated.
// Its modules (Nouns, Pronouns, Verbs, ...) teach English vocabulary and
// grammar terms themselves (e.g. 'Which word is a common noun? A) Quickly
// B) Pretty C) School D) Run'). Translating the example words into Danish
// would break the exercise, since the subject IS the English language.
// Those modules/steps are passed through unchanged from the English
// FALLBACK so English learners get the same content in both languages.
//
// portal.js picks this dataset instead of the English FALLBACK content
// when the site language is Danish (see useLanguage() / lang==='da').
//
// HOW TO EXTEND: this file is generated from several translation source
// files for maintainability (one per subject) — see module_translations_da.js
// and steps_*_da.js alongside build-da-content.js if those are kept in the
// repo. If editing directly, keep the exact same Module ID / Step Number
// keys as pages/portal.js so progress tracking and Module-ID-based lookups
// keep working when switching languages mid-session.

const QUIZ_LEARNING_MODULES_DA = [
    {"Module ID":"LM01", Title:"Planters Livscyklus", Subject:"Naturfag", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-seedling", Emoji:"🌱", "Color (Hex)":"#22c55e", Introduction:"Planter starter som små frø. Med vand, sollys og god jord vokser et frø til en spire og derefter til en høj, voksen plante. Voksne planter danner blomster, der laver nye frø — og hele cyklussen begynder forfra!", "Intro Image URL":"", "Display Order":1, Active:true, SubjectEN:"Science"},
    {"Module ID":"LM02", Title:"Solsystemet", Subject:"Naturfag", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-globe", Emoji:"🪐", "Color (Hex)":"#22c55e", Introduction:"Vores solsystem er Solen og alt, hvad der bevæger sig omkring den — otte planeter, deres måner og masser af mindre klipper og isobjekter, alt sammen holdt på plads af Solens tyngdekraft.", "Intro Image URL":"", "Display Order":2, Active:true, SubjectEN:"Science"},
    {"Module ID":"LM03", Title:"Vandets Kredsløb", Subject:"Naturfag", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-droplet", Emoji:"💧", "Color (Hex)":"#22c55e", Introduction:"Vand er altid i bevægelse! Det stiger op fra have og floder som damp, køler ned og bliver til skyer, falder ned igen som regn og strømmer tilbage til havet for at begynde rejsen forfra.", "Intro Image URL":"", "Display Order":3, Active:true, SubjectEN:"Science"},
    {"Module ID":"LM04", Title:"Menneskekroppen", Subject:"Naturfag", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-person", Emoji:"🫀", "Color (Hex)":"#22c55e", Introduction:"Din krop er et hold af fantastiske dele, der arbejder sammen — knogler, der holder dig oppe, muskler, der hjælper dig med at bevæge dig, et hjerte, der pumper blod, og lunger, der henter den luft, du indånder.", "Intro Image URL":"", "Display Order":4, Active:true, SubjectEN:"Science"},
    {"Module ID":"LM05", Title:"Brøker", Subject:"Matematik", Class:"6. klasse", "Icon (FontAwesome solid)":"fa-divide", Emoji:"➗", "Color (Hex)":"#f97316", Introduction:"En brøk viser en del af en helhed — ligesom én skive af en pizza, der er skåret i lige store stykker. Det nederste tal tæller alle skiverne; det øverste tal tæller de skiver, du har.", "Intro Image URL":"", "Display Order":5, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M01", Title:"Fiskefortællingen", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-fish", Emoji:"🐟", "Color (Hex)":"#f97316", Introduction:"Tal er overalt omkring os — selv på et fiskemarked! I dette kapitel udforsker vi meget store tal gennem historier fra det virkelige liv, lærer at læse og skrive dem og øver afrunding, estimering og pladsværdi for at forstå store mængder.", "Intro Image URL":"", "Display Order":26, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M02", Title:"Former Og Vinkler", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-shapes", Emoji:"📐", "Color (Hex)":"#f97316", Introduction:"Vinkler er overalt — i hjørnerne af en bog, viserne på et ur og benene på en stol. Dette kapitel lærer os at genkende, navngive, måle og tegne vinkler, og at udforske, hvordan forskellige former er bygget af rette linjer, der mødes i forskellige vinkler.", "Intro Image URL":"", "Display Order":27, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M03", Title:"Dele Og Helheder", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-chart-pie", Emoji:"🍕", "Color (Hex)":"#f97316", Introduction:"Når vi deler noget op i lige store stykker, er hvert stykke en brøkdel af helheden. I dette kapitel lærer vi at læse, skrive, sammenligne og lægge brøker sammen gennem sjove aktiviteter som at farvelægge gitre, dele mad og læse kort.", "Intro Image URL":"", "Display Order":28, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M04", Title:"Faktorer Og Multipla", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-hashtag", Emoji:"🔢", "Color (Hex)":"#f97316", Introduction:"Nogle tal gemmer sig inde i andre! En faktor går op i et tal uden rest, og et multiplum er det, du får, når du ganger. Dette kapitel hjælper os med at finde faktorer, opdage multipla, arbejde med primtal og bruge mfm og hfd til at løse virkelige problemer.", "Intro Image URL":"", "Display Order":29, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M05", Title:"Decimaltal", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-circle-dot", Emoji:"🔟", "Color (Hex)":"#f97316", Introduction:"Et decimalkomma åbner en verden mellem hele tal. I dette kapitel møder vi tiendedele, hundrededele og tusindedele — og øver os i at læse priser, måle længder og lægge decimaltal sammen eller trække dem fra med selvtillid.", "Intro Image URL":"", "Display Order":30, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M06", Title:"Areal Og Omkreds", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-vector-square", Emoji:"📏", "Color (Hex)":"#f97316", Introduction:"Hvor meget hegn skal der til omkring en have? Hvor mange fliser dækker et gulv? Omkreds måler afstanden rundt om en figur, og areal måler pladsen indeni. Dette kapitel opbygger begge færdigheder med rektangler, kvadrater og uregelmæssige former.", "Intro Image URL":"", "Display Order":31, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M07", Title:"Diagrammer Og Grafer", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-chart-bar", Emoji:"📊", "Color (Hex)":"#f97316", Introduction:"Tal fortæller bedre historier med billeder! I dette kapitel indsamler vi data, tegner streg-optællinger, piktogrammer og søjlediagrammer, aflæser oplysninger fra dem og besvarer spørgsmål om virkelige situationer ud fra data, vi har organiseret.", "Intro Image URL":"", "Display Order":32, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M08", Title:"Multiplikation Og Division", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-calculator", Emoji:"✖️", "Color (Hex)":"#f97316", Introduction:"Multiplikation og division er overalt i hverdagen — fra at dele slik ligeligt mellem venner til at finde ud af, hvor mange genstande der er plads til i kasser. I dette kapitel ganger og dividerer du med selvtillid, løser virkelige tekstopgaver og opdager, hvordan de to regnearter altid hænger sammen.", "Intro Image URL":"", "Display Order":33, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM_M09", Title:"Måling", Subject:"Matematik", Class:"5. klasse", "Icon (FontAwesome solid)":"fa-ruler", Emoji:"📐", "Color (Hex)":"#f97316", Introduction:"Hvor tung er din skoletaske? Hvor langt er der til den næste by? Hvor meget vand fylder en spand? Dette kapitel handler om de enheder og redskaber, vi bruger til at måle længde, vægt og rumfang — og øver omregning mellem enheder for at løse hverdagsproblemer.", "Intro Image URL":"", "Display Order":34, Active:true, SubjectEN:"Mathematics"},
    {"Module ID":"LM06", Title:"Nouns", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-tag", Emoji:"🏷️", "Color (Hex)":"#3b82f6", Introduction:"A noun is the name of a person, place, animal, thing, or idea. We use nouns every day when we talk about people, places, and objects around us.", "Now You Try":"Write one sentence that uses a common noun, a proper noun, and an abstract noun together.", "Intro Image URL":"", "Display Order":6, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM07", Title:"Pronouns", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-user", Emoji:"👤", "Color (Hex)":"#3b82f6", Introduction:"A pronoun is a word that takes the place of a noun, like he, she, it, or they. Instead of repeating a name again and again, pronouns help our sentences flow more smoothly.", "Intro Image URL":"", "Display Order":7, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM08", Title:"Verbs", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-person-running", Emoji:"🏃", "Color (Hex)":"#3b82f6", Introduction:"A verb is an action word — it tells us what someone or something is doing, like run, jump, or sing. Every sentence needs a verb to come alive!", "Intro Image URL":"", "Display Order":8, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM09", Title:"Adjectives", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-palette", Emoji:"🎨", "Color (Hex)":"#3b82f6", Introduction:"An adjective is a word that describes a noun — it tells us what something looks, feels, or seems like, like tall, red, or happy. Adjectives add colour and detail to our sentences.", "Intro Image URL":"", "Display Order":9, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM10", Title:"Adverbs", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-bolt", Emoji:"⚡", "Color (Hex)":"#3b82f6", Introduction:"An adverb describes how, when, or where an action happens, like quickly, yesterday, or outside. Adverbs often answer the question \"how?\" about a verb.", "Intro Image URL":"", "Display Order":10, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM11", Title:"Articles", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-bookmark", Emoji:"🔖", "Color (Hex)":"#3b82f6", Introduction:"Articles are the small words a, an, and the that come before nouns. They help us know whether we're talking about any one thing in general, or one special, specific thing.", "Intro Image URL":"", "Display Order":11, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM12", Title:"Prepositions", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-location-dot", Emoji:"📍", "Color (Hex)":"#3b82f6", Introduction:"A preposition is a word that shows where something is or how it relates to something else, like in, on, under, or behind. Prepositions help us describe positions and places.", "Intro Image URL":"", "Display Order":12, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM13", Title:"Conjunctions", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-link", Emoji:"🔗", "Color (Hex)":"#3b82f6", Introduction:"A conjunction is a joining word, like and, but, or because. Conjunctions connect words, phrases, or whole sentences together so our ideas flow smoothly.", "Intro Image URL":"", "Display Order":13, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM14", Title:"Subject and Predicate", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-scale-balanced", Emoji:"⚖️", "Color (Hex)":"#3b82f6", Introduction:"Every sentence has two main parts: the subject, which tells us who or what the sentence is about, and the predicate, which tells us what the subject does or is.", "Intro Image URL":"", "Display Order":14, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM15", Title:"Types of Sentences", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-comment", Emoji:"💭", "Color (Hex)":"#3b82f6", Introduction:"Sentences come in different types depending on their job — telling, asking, exclaiming, or commanding. Knowing the type helps us choose the right punctuation too!", "Intro Image URL":"", "Display Order":15, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM16", Title:"Punctuation", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-pen", Emoji:"✏️", "Color (Hex)":"#3b82f6", Introduction:"Punctuation marks — like full stops, question marks, commas, and exclamation marks — are the little signals that help readers know how to read a sentence.", "Intro Image URL":"", "Display Order":16, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM17", Title:"Direct and Indirect Speech", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-comments", Emoji:"💬", "Color (Hex)":"#3b82f6", Introduction:"Direct speech repeats someone's exact words inside quotation marks. Indirect speech reports what someone said, without quoting them word for word. Both ways let us share what people say!", "Intro Image URL":"", "Display Order":17, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM18", Title:"Synonyms", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-arrows-rotate", Emoji:"🔄", "Color (Hex)":"#3b82f6", Introduction:"Synonyms are words that mean almost the same thing, like happy and glad. Knowing synonyms helps us choose just the right word and avoid repeating ourselves.", "Intro Image URL":"", "Display Order":18, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM19", Title:"Antonyms", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-arrows-left-right", Emoji:"↔️", "Color (Hex)":"#3b82f6", Introduction:"Antonyms are words with opposite meanings, like hot and cold, or big and small. Spotting antonyms helps us understand and describe differences clearly.", "Intro Image URL":"", "Display Order":19, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM20", Title:"Homophones", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-ear-listen", Emoji:"👂", "Color (Hex)":"#3b82f6", Introduction:"Homophones are words that sound exactly the same but have different spellings and meanings, like their and there. Learning them helps us write the correct word every time.", "Intro Image URL":"", "Display Order":20, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM21", Title:"Vocabulary Building", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-book", Emoji:"📖", "Color (Hex)":"#3b82f6", Introduction:"Vocabulary building means learning new words and understanding what they mean, so we can read, write, and speak with more confidence and variety.", "Intro Image URL":"", "Display Order":21, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM22", Title:"Sentence Formation", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-puzzle-piece", Emoji:"🧩", "Color (Hex)":"#3b82f6", Introduction:"Sentence formation is about putting words together in the right order, so our sentences make complete sense and clearly share our ideas.", "Intro Image URL":"", "Display Order":22, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM23", Title:"Letter Writing", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-envelope", Emoji:"✉️", "Color (Hex)":"#3b82f6", Introduction:"Letter writing teaches us how to write a friendly, well-organised letter — with a greeting, a clear message, and a warm closing — to share news with someone we care about.", "Intro Image URL":"", "Display Order":23, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM24", Title:"Reading Comprehension", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-book-open-reader", Emoji:"📚", "Color (Hex)":"#3b82f6", Introduction:"Reading comprehension is the skill of understanding what we read — finding facts, figuring out meanings, and following a story from beginning to end.", "Intro Image URL":"", "Display Order":24, Active:true, SubjectEN:"English Grammar"},
    {"Module ID":"LM25", Title:"Creative Writing", Subject:"English Grammar", Class:"Class 5", "Icon (FontAwesome solid)":"fa-feather", Emoji:"✍️", "Color (Hex)":"#3b82f6", Introduction:"Creative writing lets our imagination shine! It's about telling our own stories, describing scenes vividly, and putting our ideas into well-organised paragraphs.", "Intro Image URL":"", "Display Order":25, Active:true, SubjectEN:"English Grammar"}
];

const QUIZ_LEARNING_STEPS_DA = [
    {"Module ID":"LM01", "Step Number":1, "Learning Section":"Hvad er en plante?", Teaching:"Planter er levende væsener, der laver deres egen mad ved hjælp af sollys, vand og luft — de spiser ikke andre levende væsener, sådan som dyr gør.", "Step Image URL":"", Question:"Hvad er sandt om planter?", "Option A":"De spiser andre levende væsener", "Option B":"De laver deres egen mad ved hjælp af sollys", "Option C":"De kan gå for at finde mad", "Option D":"De er ikke levende væsener", "Correct Option":"B", Explanation:"Korrekt! Planter laver deres egen mad gennem en proces, der kaldes fotosyntese, ved hjælp af sollys, vand og luft.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":2, "Learning Section":"Hvad er en plante?", Teaching:"Planter findes næsten overalt på Jorden — i haver, skove, ørkener og damme — fordi forskellige planter har tilpasset sig til at overleve forskellige steder.", "Step Image URL":"", Question:"Hvor kan planter findes?", "Option A":"Kun i haver", "Option B":"Kun i skove", "Option C":"Næsten overalt, herunder ørkener og damme", "Option D":"Kun hvor det regner meget", "Correct Option":"C", Explanation:"Rigtigt! Planter har tilpasset sig til at leve i mange forskellige miljøer, fra tørre ørkener til våde damme.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":3, "Learning Section":"Hvad er en plante?", Teaching:"Ligesom alle levende væsener bliver en plante født, vokser, formerer sig og dør til sidst — hele denne rejse kaldes dens livscyklus.", "Step Image URL":"", Question:"Hvad kalder vi den rejse, en plante tager fra at blive født til at producere nye planter?", "Option A":"Planters livscyklus", "Option B":"Plantefamilie", "Option C":"Planterige", "Option D":"Planters levested", "Correct Option":"A", Explanation:"Ja! Hver plante gennemgår faser, fra frø til at lave nye frø — og hele den rejse er dens livscyklus.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":4, "Learning Section":"Hvad er et frø?", Teaching:"Et frø er en lille pakke lavet af en plante, der indeholder en babyplante indeni, sammen med noget oplagret mad, der hjælper den med at begynde at vokse.", "Step Image URL":"", Question:"Hvad indeholder et frø indeni?", "Option A":"En babyplante og oplagret mad", "Option B":"Kun vand", "Option C":"Kun jord", "Option D":"En fuldt udvokset plante", "Correct Option":"A", Explanation:"Korrekt! Inde i hvert frø er der en lille babyplante (kimen) plus et lille forråd af mad til dens første dage med vækst.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":5, "Learning Section":"Hvad er et frø?", Teaching:"Frø findes i mange former, størrelser og farver — fra et lille sennepsfrø til et stort kokosfrø.", "Step Image URL":"", Question:"Hvilket udsagn om frø er korrekt?", "Option A":"Alle frø ser præcis ens ud", "Option B":"Frø kan have mange forskellige former, størrelser og farver", "Option C":"Frø er altid grønne", "Option D":"Frø er altid runde", "Correct Option":"B", Explanation:"Rigtigt! Sammenlign bare et lille sennepsfrø med et kæmpe kokosfrø — frø varierer enormt.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":6, "Learning Section":"Hvad er et frø?", Teaching:"De fleste frø har en hård yderskal kaldet frøskallen, som beskytter babyplanten indeni, indtil forholdene er rigtige for den til at vokse.", "Step Image URL":"", Question:"Hvad beskytter babyplanten inde i et frø?", "Option A":"Bladet", "Option B":"Frøskallen", "Option C":"Blomsten", "Option D":"Roden", "Correct Option":"B", Explanation:"Ja! Den hårde frøskal beskytter den sarte kim, indtil det er tid til at spire.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":7, "Learning Section":"Hvordan sker spiring?", Teaching:"Spiring er processen, hvor et frø vågner og begynder at spire, og dermed starter sin rejse til at blive en ung plante.", "Step Image URL":"", Question:"Hvad er spiring?", "Option A":"Et frø, der bliver til en blomst med det samme", "Option B":"Et frø, der begynder at spire og vokse", "Option C":"En plante, der mister sine blade", "Option D":"Et frø, der bliver spist", "Correct Option":"B", Explanation:"Korrekt! Spiring er simpelthen den første vækstfase, hvor den lille plante inde i frøet begynder at vokse.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":8, "Learning Section":"Hvordan sker spiring?", Teaching:"Under spiring revner frøskallen, mens en lille rod vokser nedad, og et skud vokser opad.", "Step Image URL":"", Question:"Hvad sker der først, når et frø spirer?", "Option A":"Frøskallen revner, og en rod og et skud begynder at vokse", "Option B":"Planten danner blomster med det samme", "Option C":"Frøet bliver til sten", "Option D":"Frøet flyver væk", "Correct Option":"A", Explanation:"Rigtigt! Roden vokser nedad for at forankre planten og optage vand, mens skuddet vokser opad mod lyset.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":9, "Learning Section":"Hvordan sker spiring?", Teaching:"Ikke alle frø spirer med samme hastighed — nogle spirer på få dage, mens andre kan tage uger, afhængigt af frøet og forholdene omkring det.", "Step Image URL":"", Question:"Tager alle frø lige lang tid om at spire?", "Option A":"Ja, altid præcis 7 dage", "Option B":"Nej, det varierer med frøtype og forhold", "Option C":"Intet frø spirer nogensinde", "Option D":"Ja, alle frø tager et år", "Correct Option":"B", Explanation:"Korrekt! Spiringstiden afhænger af frøtypen og af forhold som temperatur og fugtighed.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":10, "Learning Section":"Hvad har et frø brug for for at vokse?", Teaching:"Et frø har brug for vand, luft og den rette temperatur for at spire og begynde at vokse.", "Step Image URL":"", Question:"Hvad af følgende har et frø brug for for at spire?", "Option A":"Vand, luft og den rette temperatur", "Option B":"Kun mørke", "Option C":"Kun sand", "Option D":"Høj støj", "Correct Option":"A", Explanation:"Ja! Vand blødgør frøskallen og igangsætter væksten, luft giver ilt, og varme hjælper processen på vej.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":11, "Learning Section":"Hvad har et frø brug for for at vokse?", Teaching:"Når en spire er begyndt at spire, har den også brug for sollys for at fortsætte med at vokse stærk og sund.", "Step Image URL":"", Question:"Hvorfor har en voksende spire brug for sollys?", "Option A":"For at lave sin egen mad gennem fotosyntese", "Option B":"For at lave støj", "Option C":"For kun at skifte farve", "Option D":"Sollys er ikke nødvendigt", "Correct Option":"A", Explanation:"Korrekt! Når den har fået blade, bruger den unge plante sollys til at lave sin egen mad og fortsætte med at vokse.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":12, "Learning Section":"Hvad har et frø brug for for at vokse?", Teaching:"God jord giver en voksende plante næringsstoffer at optage og et stabilt sted for dens rødder at forankre sig og brede sig.", "Step Image URL":"", Question:"Hvad giver jord til en voksende plante?", "Option A":"Næringsstoffer og et sted for rødderne at forankre sig", "Option B":"Kun farve", "Option C":"Kun vægt", "Option D":"Intet vigtigt", "Correct Option":"A", Explanation:"Rigtigt! Jorden holder på de næringsstoffer, rødderne optager, og giver planten et stabilt sted at vokse.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":13, "Learning Section":"Hvad er en spire?", Teaching:"En spire er en ung plante, der lige er spiret fra et frø, som regel med sine allerførste små blade.", "Step Image URL":"", Question:"Hvad kalder vi en ung plante, der lige er spiret?", "Option A":"En spire", "Option B":"En blomst", "Option C":"En frugt", "Option D":"En rod", "Correct Option":"A", Explanation:"Korrekt! En spire er den allerførste plantefase efter spiring, ofte bare en tynd stængel med ét eller to små blade.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":14, "Learning Section":"Hvad er en spire?", Teaching:"En spires første blade hjælper den med at begynde at lave sin egen mad gennem fotosyntese så hurtigt som muligt.", "Step Image URL":"", Question:"Hvad er funktionen af en spires første blade?", "Option A":"At hjælpe den med at begynde at lave mad via fotosyntese", "Option B":"At tiltrække dyr", "Option C":"At lave frø med det samme", "Option D":"At beskytte rødderne", "Correct Option":"A", Explanation:"Ja! Disse første små blade er afgørende — de lader spiren begynde at fange sollys til at drive sin vækst.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":15, "Learning Section":"Hvad er en spire?", Teaching:"Spirer er sarte og kan let blive beskadiget, så gartnere og landmænd beskytter dem ofte mod hårdt vejr og sultne dyr.", "Step Image URL":"", Question:"Hvorfor anses spirer for sarte?", "Option A":"De bliver let beskadiget af vejr eller dyr", "Option B":"De er lavet af sten", "Option C":"De kan ikke spises af noget", "Option D":"De er tungere end voksne planter", "Correct Option":"A", Explanation:"Korrekt! Unge spirer har endnu ikke udviklet den hårdførhed, som en voksen plante har.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":16, "Learning Section":"Hvordan dannes en voksen plante?", Teaching:"Mens en spire fortsætter med at optage sollys, vand og næringsstoffer, vokser den højere og udvikler en stærkere stængel, flere blade og rødder — og bliver til en voksen plante.", "Step Image URL":"", Question:"Hvad hjælper en spire med at vokse til en voksen plante?", "Option A":"Fortsat sollys, vand og næringsstoffer", "Option B":"At blive i mørket", "Option C":"At fjerne dens rødder", "Option D":"At undgå vand", "Correct Option":"A", Explanation:"Rigtigt! Jævn adgang til sollys, vand og næringsstoffer lader planten fortsætte med at danne nye celler og vokse sig større.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":17, "Learning Section":"Hvordan dannes en voksen plante?", Teaching:"En voksen plante har et fuldt udviklet rodsystem, stængel og blade, og er klar til at formere sig ved at danne blomster.", "Step Image URL":"", Question:"Hvad gør en plante \"voksen\"?", "Option A":"Den har fuldt udviklede rødder, stængel, blade og kan formere sig", "Option B":"Den er blevet brun", "Option C":"Den er stoppet med at vokse for altid", "Option D":"Den har mistet alle sine blade", "Correct Option":"A", Explanation:"Korrekt! At være voksen betyder, at planten har alt, hvad den har brug for til at klare sig selv og starte næste fase — at danne blomster og frø.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":18, "Learning Section":"Hvordan dannes en voksen plante?", Teaching:"Forskellige planter bruger meget forskellig tid på at blive voksne — nogle urter bliver voksne på få uger, mens nogle træer tager år.", "Step Image URL":"", Question:"Bruger alle planter den samme tid på at blive voksne?", "Option A":"Ja, præcis én måned for hver plante", "Option B":"Nej, det varierer — nogle tager uger, andre tager år", "Option C":"Alle planter bliver voksne på én dag", "Option D":"Planter bliver aldrig voksne", "Correct Option":"B", Explanation:"Ja! En tomatplante kan blive voksen på uger, mens et egetræ kan tage mange år.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":19, "Learning Section":"Hvordan er blomster involveret?", Teaching:"Mange voksne planter danner blomster, som indeholder de dele, der skal til for at producere nye frø.", "Step Image URL":"", Question:"Hvad er blomstens hovedopgave i en plantes livscyklus?", "Option A":"At hjælpe med at producere nye frø", "Option B":"At gøre planten højere", "Option C":"At optage vand", "Option D":"At beskytte rødderne", "Correct Option":"A", Explanation:"Korrekt! Blomster indeholder plantens formeringsdele og er afgørende for at lave den næste generation af frø.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":20, "Learning Section":"Hvordan er blomster involveret?", Teaching:"Bestøvning sker, når pollen flytter sig fra én blomst til en anden, ofte transporteret af insekter som bier, eller af vinden.", "Step Image URL":"", Question:"Hvad er bestøvning?", "Option A":"Pollen, der flytter sig fra én blomst til en anden", "Option B":"Et frø, der spirer", "Option C":"Et blad, der falder af", "Option D":"Vand, der trænger ned i jorden", "Correct Option":"A", Explanation:"Rigtigt! Bier, sommerfugle og vind er almindelige transportører, der flytter pollen mellem blomster, så frø kan dannes.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":21, "Learning Section":"Hvordan er blomster involveret?", Teaching:"Efter vellykket bestøvning kan en blomst udvikle sig til en frugt, der opbevarer de nye frø sikkert indeni.", "Step Image URL":"", Question:"Hvad kan en bestøvet blomst udvikle sig til?", "Option A":"En frugt, der indeholder frø", "Option B":"En sten", "Option C":"En rod", "Option D":"Jord", "Correct Option":"A", Explanation:"Korrekt! Mange frugter — som æbler, tomater og bønner — er simpelthen den del af planten, der voksede for at beskytte og bære frø.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":22, "Learning Section":"Hvordan produceres nye frø?", Teaching:"Når bestøvningen er fuldført, udvikler en del af blomsten sig til en frugt, og frø dannes sikkert indeni, klar til at starte cyklussen igen.", "Step Image URL":"", Question:"Hvor dannes nye frø efter bestøvning?", "Option A":"Inde i den udviklende frugt", "Option B":"Direkte i jorden", "Option C":"På kronbladene", "Option D":"I luften", "Correct Option":"A", Explanation:"Ja! Den befrugtede del af blomsten svulmer op til en frugt, og frøene udvikler sig sikkert indeni.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":23, "Learning Section":"Hvordan produceres nye frø?", Teaching:"Når frøene er klar, kan de sprede sig til nye steder — transporteret af vind, vand, dyr eller blot ved at falde til jorden i nærheden.", "Step Image URL":"", Question:"Hvordan kan nye frø sprede sig for at vokse andre steder?", "Option A":"Ved at vind, vand eller dyr bærer dem", "Option B":"De kan kun blive præcis, hvor de blev dannet", "Option C":"De opløses i regn", "Option D":"De bliver til sten", "Correct Option":"A", Explanation:"Korrekt! Frø har smarte måder at rejse på — fnuggede frø flyder med vinden, klæbrige frø hænger fast i dyrepels, og nogle flyder på vand.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM01", "Step Number":24, "Learning Section":"Hvordan produceres nye frø?", Teaching:"Når et spredt frø lander et sted med den rette mængde vand, luft og varme, kan det spire — og hele plantens livscyklus begynder igen.", "Step Image URL":"", Question:"Hvad sker der, når et nyt frø lander på et godt sted?", "Option A":"Det kan spire og starte livscyklussen igen", "Option B":"Det forsvinder for altid", "Option C":"Det bliver til en blomst med det samme uden at vokse", "Option D":"Der sker ikke noget", "Correct Option":"A", Explanation:"Det er den smukkeste del af livscyklussen — hvert nyt frø har potentialet til at vokse til en helt ny plante og starte hele rejsen forfra.", "Learn More URL":"https://www.ncert.nic.in/textbook/pdf/eeap105.pdf", "Learn More Label":"Læs NCERT-kapitlet: Frø og Frø", Active:true},
    {"Module ID":"LM_M01", "Step Number":1, "Learning Section":"Store Tal", "Icon (FontAwesome solid)":"fa-fish", Teaching:"Tal kan være meget store — som antallet af fisk solgt på et marked på et år! Vi bruger pladsværdi til at læse og skrive store tal. I 358.204 står 3-tallet på hundredetusinde-pladsen, 5-tallet på titusinde-pladsen, og så videre.", "Step Image URL":"", Question:"Hvad er pladsværdien af cifret 5 i tallet 358.204?", "Option A":"Enere", "Option B":"Hundreder", "Option C":"Tusinder", "Option D":"Titusinder", "Correct Option":"C", Explanation:"Korrekt! I 358.204 er rækkefølgen fra venstre: 3 (hundredetusinder), 5 (titusinder), 8 (tusinder), 2 (hundreder), 0 (tiere), 4 (enere). Så cifret 5 står på titusinde-pladsen. Flot klaret!", Active:true},
    {"Module ID":"LM_M01", "Step Number":2, "Learning Section":"Store Tal", Teaching:"Estimering betyder at finde et omtrentligt svar ved at runde af. Vi runder af til nærmeste 10, 100 eller 1000, afhængigt af hvor præcist vi har brug for det.", "Step Image URL":"", Question:"En fisker fangede 4.738 fisk på en måned. Afrundet til nærmeste tusind, hvor mange fisk fangede han?", "Option A":"4.000", "Option B":"5.000", "Option C":"4.700", "Option D":"4.800", "Correct Option":"B", Explanation:"Rigtigt! 4.738 ligger tættere på 5.000 end på 4.000 — cifret på hundrede-pladsen (7) er 5 eller derover, så vi runder op.", Active:true},
    {"Module ID":"LM_M01", "Step Number":3, "Learning Section":"Sammenligning Af Store Tal", Teaching:"For at sammenligne store tal skal man først sammenligne antallet af cifre. Hvis de har samme antal cifre, sammenligner man fra det yderste venstre ciffer.", "Step Image URL":"", Question:"Hvilket tal er størst: 204.567 eller 240.567?", "Option A":"204.567", "Option B":"240.567", "Option C":"De er ens", "Option D":"Kan ikke sammenlignes", "Correct Option":"B", Explanation:"Korrekt! Begge tal har 6 cifre. Sammenlignet fra venstre: 2=2, derefter 0 mod 4 — da 4 > 0, er tallet 240.567 størst.", Active:true},
    {"Module ID":"LM_M02", "Step Number":1, "Learning Section":"Hvad Er En Vinkel?", Teaching:"En vinkel dannes, når to stråler mødes i et fælles punkt kaldet toppunktet. Drejningen mellem de to stråler er vinklens størrelse.", "Step Image URL":"", Question:"Hvad kalder vi det punkt, hvor de to stråler i en vinkel mødes?", "Option A":"Midtpunkt", "Option B":"Toppunkt", "Option C":"Kant", "Option D":"Kun et hjørne", "Correct Option":"B", Explanation:"Korrekt! Mødepunktet mellem de to stråler kaldes vinklens toppunkt.", Active:true},
    {"Module ID":"LM_M02", "Step Number":2, "Learning Section":"Typer Af Vinkler", Teaching:"En ret vinkel måler præcis 90°. En spids vinkel er mindre end 90°. En stump vinkel er mere end 90°, men mindre end 180°. En lige vinkel er præcis 180°.", "Step Image URL":"", Question:"En vinkel, der måler 65°, kaldes en _____ vinkel.", "Option A":"Ret", "Option B":"Stump", "Option C":"Spids", "Option D":"Lige", "Correct Option":"C", Explanation:"Flot klaret! 65° er mindre end 90°, så det er en spids vinkel.", Active:true},
    {"Module ID":"LM_M02", "Step Number":3, "Learning Section":"Vinkler Omkring Os", Teaching:"Viserne på et ur danner forskellige vinkler på forskellige tidspunkter. Klokken 3 danner viserne en ret vinkel (90°). Klokken 6 danner de en lige vinkel (180°).", "Step Image URL":"", Question:"Hvilken vinkel danner urets visere klokken 3?", "Option A":"45°", "Option B":"90°", "Option C":"180°", "Option D":"270°", "Correct Option":"B", Explanation:"Korrekt! Klokken 3 peger minutviseren på 12, og timeviseren peger på 3 — det danner en ret vinkel på 90°.", Active:true},
    {"Module ID":"LM_M03", "Step Number":1, "Learning Section":"At Forstå Brøker", Teaching:"En brøk repræsenterer en del af en helhed. Når vi deler en helhed i lige store dele og tager nogle af dem, skriver vi det som en brøk. Det nederste tal (nævneren) fortæller, hvor mange lige store dele helheden er delt i; det øverste tal (tælleren) fortæller, hvor mange dele vi har.", "Step Image URL":"", Question:"En chokoladeplade er delt i 8 lige store stykker. Riya spiser 3 stykker. Hvilken brøk spiste hun?", "Option A":"8/3", "Option B":"5/8", "Option C":"3/8", "Option D":"3/5", "Correct Option":"C", Explanation:"Korrekt! 3 stykker ud af 8 lige store stykker = 3/8.", Active:true},
    {"Module ID":"LM_M03", "Step Number":2, "Learning Section":"Sammenligning Af Brøker", Teaching:"Når brøker har samme nævner (nederste tal), er den med den største tæller (øverste tal) størst.", "Step Image URL":"", Question:"Hvilken brøk er størst: 5/9 eller 7/9?", "Option A":"5/9", "Option B":"7/9", "Option C":"De er ens", "Option D":"Kan ikke sammenlignes", "Correct Option":"B", Explanation:"Flot klaret! Begge brøker har samme nævner, 9, så vi sammenligner tællerne: 7 > 5, så 7/9 er størst.", Active:true},
    {"Module ID":"LM_M03", "Step Number":3, "Learning Section":"At Lægge Brøker Sammen", Teaching:"For at lægge brøker med samme nævner sammen lægger man bare tællerne sammen og beholder nævneren.", "Step Image URL":"", Question:"Hvad er 2/7 + 3/7?", "Option A":"5/14", "Option B":"6/7", "Option C":"5/7", "Option D":"2/14", "Correct Option":"C", Explanation:"Korrekt! Læg tællerne sammen: 2 + 3 = 5. Behold nævneren: 7. Svar = 5/7.", Active:true},
    {"Module ID":"LM_M04", "Step Number":1, "Learning Section":"Faktorer", Teaching:"En faktor i et tal går op i det uden rest. For eksempel er faktorerne i 12: 1, 2, 3, 4, 6 og 12 — hver af dem går nøjagtigt op i 12.", "Step Image URL":"", Question:"Hvilken af disse er IKKE en faktor i 24?", "Option A":"4", "Option B":"6", "Option C":"7", "Option D":"8", "Correct Option":"C", Explanation:"Korrekt! 24 ÷ 7 = 3 med rest 3, så 7 er ikke en faktor i 24.", Active:true},
    {"Module ID":"LM_M04", "Step Number":2, "Learning Section":"Multipla", Teaching:"Et multiplum af et tal er, hvad man får, når man ganger det med 1, 2, 3, 4, og så videre. De første fem multipla af 4 er 4, 8, 12, 16 og 20.", "Step Image URL":"", Question:"Hvilken af disse er et multiplum af 7?", "Option A":"25", "Option B":"36", "Option C":"49", "Option D":"50", "Correct Option":"C", Explanation:"Flot klaret! 7 × 7 = 49, så 49 er et multiplum af 7.", Active:true},
    {"Module ID":"LM_M04", "Step Number":3, "Learning Section":"Primtal", Teaching:"Et primtal har præcis to faktorer — 1 og sig selv. For eksempel er 7 et primtal, fordi kun 1 × 7 = 7. Et sammensat tal har mere end to faktorer.", "Step Image URL":"", Question:"Hvilket af følgende er et primtal?", "Option A":"9", "Option B":"15", "Option C":"11", "Option D":"21", "Correct Option":"C", Explanation:"Korrekt! 11 har kun to faktorer — 1 og 11 — så det er et primtal. 9 = 3×3, 15 = 3×5, 21 = 3×7, så de er sammensatte tal.", Active:true},
    {"Module ID":"LM_M05", "Step Number":1, "Learning Section":"At Forstå Decimaltal", Teaching:"Et decimalkomma adskiller den hele tal-del fra brøkdelen. I 3,7 er 3 det hele tal, og 7 er 7 tiendedele — det betyder syv ud af ti lige store dele.", "Step Image URL":"", Question:"I decimaltallet 5,3, hvad repræsenterer cifret 3?", "Option A":"3 enere", "Option B":"3 tiendedele", "Option C":"3 hundrededele", "Option D":"3 tiere", "Correct Option":"B", Explanation:"Korrekt! Cifret efter decimalkommaet står på tiendedele-pladsen. Så 3-tallet i 5,3 repræsenterer 3 tiendedele.", Active:true},
    {"Module ID":"LM_M05", "Step Number":2, "Learning Section":"Sammenligning Af Decimaltal", Teaching:"For at sammenligne decimaltal skal man først sammenligne de hele tal-dele. Hvis de er ens, sammenligner man tiendedele-cifrene, derefter hundrededele-cifrene, og så videre.", "Step Image URL":"", Question:"Hvilket decimaltal er størst: 4,7 eller 4,3?", "Option A":"4,3", "Option B":"4,7", "Option C":"De er ens", "Option D":"Kan ikke sammenlignes", "Correct Option":"B", Explanation:"Flot klaret! De hele tal-dele er begge 4, så sammenlign tiendedelene: 7 > 3, så 4,7 > 4,3.", Active:true},
    {"Module ID":"LM_M05", "Step Number":3, "Learning Section":"At Lægge Decimaltal Sammen", Teaching:"For at lægge decimaltal sammen skal man rette decimalkommaerne ind under hinanden og derefter lægge sammen ligesom hele tal. Decimalkommaet i svaret kommer direkte under decimalkommaerne i de tal, du lagde sammen.", "Step Image URL":"", Question:"Hvad er 2,5 + 1,3?", "Option A":"3,8", "Option B":"38", "Option C":"3,08", "Option D":"4,8", "Correct Option":"A", Explanation:"Korrekt! 2,5 + 1,3: læg tiendedelene sammen (5+3=8) og enerne (2+1=3). Svar = 3,8.", Active:true},
    {"Module ID":"LM_M06", "Step Number":1, "Learning Section":"Omkreds", Teaching:"Omkreds er den samlede afstand rundt om en figur. For et rektangel er Omkreds = 2 × (Længde + Bredde). For et kvadrat er Omkreds = 4 × Side.", "Step Image URL":"", Question:"Hvad er omkredsen af et rektangel, der er 8 cm langt og 5 cm bredt?", "Option A":"40 cm", "Option B":"26 cm", "Option C":"13 cm", "Option D":"16 cm", "Correct Option":"B", Explanation:"Korrekt! Omkreds = 2 × (8 + 5) = 2 × 13 = 26 cm.", Active:true},
    {"Module ID":"LM_M06", "Step Number":2, "Learning Section":"Areal", Teaching:"Areal er den mængde overflade, en figur dækker. For et rektangel er Areal = Længde × Bredde. For et kvadrat er Areal = Side × Side.", "Step Image URL":"", Question:"Hvad er arealet af et rektangel, der er 9 cm langt og 4 cm bredt?", "Option A":"26 kvadratcentimeter", "Option B":"13 kvadratcentimeter", "Option C":"36 kvadratcentimeter", "Option D":"32 kvadratcentimeter", "Correct Option":"C", Explanation:"Flot klaret! Areal = 9 × 4 = 36 kvadratcentimeter.", Active:true},
    {"Module ID":"LM_M06", "Step Number":3, "Learning Section":"Areal Mod Omkreds", Teaching:"Omkreds og areal er forskellige målinger. Omkreds måler grænsen (afstanden rundt om), mens areal måler den dækkede overflade (pladsen indeni).", "Step Image URL":"", Question:"En kvadratisk have har en side på 7 m. Hvad er dens areal?", "Option A":"28 kvadratmeter", "Option B":"14 kvadratmeter", "Option C":"49 kvadratmeter", "Option D":"21 kvadratmeter", "Correct Option":"C", Explanation:"Korrekt! Areal af et kvadrat = Side × Side = 7 × 7 = 49 kvadratmeter.", Active:true},
    {"Module ID":"LM_M07", "Step Number":1, "Learning Section":"Stregoptælling", Teaching:"Stregoptælling er en hurtig måde at tælle på. Vi tegner fire lodrette streger og derefter en diagonal femte streg hen over dem for at lave en gruppe på 5. Det gør det nemt at tælle store mængder hurtigt.", "Step Image URL":"", Question:"Hvor mange repræsenterer en optællingsgruppe med fire lodrette streger og én diagonal streg hen over dem?", "Option A":"4", "Option B":"5", "Option C":"6", "Option D":"10", "Correct Option":"B", Explanation:"Korrekt! En gruppe af 4 streger krydset af 1 diagonal = 5. Dette er den almindelige optællingsmarkering for 5.", Active:true},
    {"Module ID":"LM_M07", "Step Number":2, "Learning Section":"Piktogrammer", Teaching:"Et piktogram bruger billeder eller symboler til at vise data. Hvert symbol repræsenterer et fast antal ting. En signaturforklaring fortæller os, hvad hvert symbol står for.", "Step Image URL":"", Question:"I et piktogram svarer ét æble-symbol til 4 æbler. Hvis en række viser 3 æble-symboler, hvor mange æbler repræsenterer det så?", "Option A":"3", "Option B":"7", "Option C":"12", "Option D":"34", "Correct Option":"C", Explanation:"Flot klaret! 3 symboler × 4 æbler hver = 12 æbler.", Active:true},
    {"Module ID":"LM_M07", "Step Number":3, "Learning Section":"Søjlediagrammer", Teaching:"Et søjlediagram bruger rektangulære søjler til at vise data. Højden (eller længden) af hver søjle repræsenterer værdien for den kategori. Vi aflæser værdien ved at se, hvor søjlen ender på skalaen.", "Step Image URL":"", Question:"I et søjlediagram når søjlen for \"mandag\" værdien 15. Søjlen for \"tirsdag\" når 25. Hvilken dag blev der registreret flest ting?", "Option A":"Mandag", "Option B":"Tirsdag", "Option C":"Begge er ens", "Option D":"Kan ikke afgøres", "Correct Option":"B", Explanation:"Korrekt! Den højeste søjle (25) hører til tirsdag, så der blev registreret flest ting tirsdag.", Active:true},
    {"Module ID":"LM_M08", "Step Number":1, "Learning Section":"Multiplikation Som Gentagen Addition", Teaching:"Multiplikation er en hurtig måde at lave gentagen addition på. I stedet for at lægge det samme tal sammen mange gange, ganger vi. For eksempel er 4+4+4 det samme som 3×4=12.", "Step Image URL":"", Question:"Der er 6 kasser. Hver kasse har 8 blyanter. Hvor mange blyanter er der i alt?", "Option A":"14", "Option B":"36", "Option C":"48", "Option D":"56", "Correct Option":"C", Explanation:"Korrekt! 6 kasser × 8 blyanter hver = 6 × 8 = 48 blyanter.", Active:true},
    {"Module ID":"LM_M08", "Step Number":2, "Learning Section":"Division Som Ligelig Deling", Teaching:"Division betyder at dele et tal op i lige store grupper. Hvis du har 36 slik og vil dele dem ligeligt mellem 4 venner, får hver ven 36 ÷ 4 = 9 slik.", "Step Image URL":"", Question:"72 bøger er fordelt ligeligt på 9 hylder. Hvor mange bøger er der på hver hylde?", "Option A":"7", "Option B":"8", "Option C":"9", "Option D":"63", "Correct Option":"B", Explanation:"Flot klaret! 72 ÷ 9 = 8 bøger på hver hylde.", Active:true},
    {"Module ID":"LM_M08", "Step Number":3, "Learning Section":"Sammenhængen Mellem Multiplikation Og Division", Teaching:"Multiplikation og division er omvendte regnearter — de ophæver hinanden. Hvis 7 × 8 = 56, så er 56 ÷ 7 = 8 og 56 ÷ 8 = 7. Disse kaldes en regnefamilie.", "Step Image URL":"", Question:"Hvis 9 × 6 = 54, hvilket af følgende er korrekt?", "Option A":"54 ÷ 9 = 7", "Option B":"54 ÷ 6 = 9", "Option C":"54 ÷ 6 = 7", "Option D":"54 ÷ 9 = 5", "Correct Option":"B", Explanation:"Korrekt! Da 9 × 6 = 54, giver 54 divideret med 6 svaret 9. De er en multiplikations-divisions regnefamilie.", Active:true},
    {"Module ID":"LM_M09", "Step Number":1, "Learning Section":"Længdeenheder", Teaching:"Vi måler længde med enheder som millimeter (mm), centimeter (cm), meter (m) og kilometer (km). Omregningerne er: 10 mm = 1 cm, 100 cm = 1 m, og 1000 m = 1 km.", "Step Image URL":"", Question:"Hvor mange centimeter er der i 3 meter?", "Option A":"30 cm", "Option B":"300 cm", "Option C":"3000 cm", "Option D":"3 cm", "Correct Option":"B", Explanation:"Korrekt! 1 meter = 100 centimeter, så 3 meter = 3 × 100 = 300 centimeter.", Active:true},
    {"Module ID":"LM_M09", "Step Number":2, "Learning Section":"Vægtenheder", Teaching:"Vi måler vægt med milligram (mg), gram (g) og kilogram (kg). Omregningerne er: 1000 mg = 1 g og 1000 g = 1 kg.", "Step Image URL":"", Question:"En pose ris vejer 2 kg 500 g. Hvad er dens samlede vægt i gram?", "Option A":"2500 g", "Option B":"250 g", "Option C":"25000 g", "Option D":"2050 g", "Correct Option":"A", Explanation:"Flot klaret! 2 kg = 2000 g. 2000 g + 500 g = 2500 g.", Active:true},
    {"Module ID":"LM_M09", "Step Number":3, "Learning Section":"Rumfangsenheder", Teaching:"Vi måler rumfanget af væsker med milliliter (ml) og liter (l). Omregningen er: 1000 ml = 1 liter.", "Step Image URL":"", Question:"En flaske rummer 2 liter vand. Hvor mange milliliter er det?", "Option A":"200 ml", "Option B":"20 ml", "Option C":"2000 ml", "Option D":"20000 ml", "Correct Option":"C", Explanation:"Korrekt! 1 liter = 1000 milliliter, så 2 liter = 2 × 1000 = 2000 ml.", Active:true},
    {"Module ID":"LM02", "Step Number":1, Teaching:"Solen er en kæmpe, glødende stjerne i centrum af vores solsystem.", "Step Image URL":"", Question:"Hvad er i centrum af solsystemet?", "Option A":"Jorden", "Option B":"Månen", "Option C":"Solen", "Option D":"Mars", "Correct Option":"C", Explanation:"Netop! Solen sidder i centrum, og alt andet bevæger sig rundt om den.", Active:true},
    {"Module ID":"LM02", "Step Number":2, Teaching:"Planeter bevæger sig rundt om Solen langs en bane, der kaldes en kredsløbsbane.", "Step Image URL":"", Question:"Hvad kalder vi den bane, en planet følger rundt om Solen?", "Option A":"En kredsløbsbane", "Option B":"En tunnel", "Option C":"En bro", "Option D":"En spiral", "Correct Option":"A", Explanation:"Rigtigt! Hver planet følger sin egen kredsløbsbane rundt om Solen.", Active:true},
    {"Module ID":"LM02", "Step Number":3, Teaching:"Jorden er den tredje planet fra Solen — netop den rette afstand til flydende vand.", "Step Image URL":"", Question:"Hvilken planet er nummer tre fra Solen?", "Option A":"Venus", "Option B":"Jorden", "Option C":"Jupiter", "Option D":"Merkur", "Correct Option":"B", Explanation:"Korrekt! Jorden er den tredje planet — tæt nok på Solen til at understøtte liv.", Active:true},
    {"Module ID":"LM03", "Step Number":1, Teaching:"Solen opvarmer vand i have og søer og omdanner det til usynlig damp — det er fordampning.", "Step Image URL":"", Question:"Hvad sker der, når Solen opvarmer vandet i en sø?", "Option A":"Det fryser", "Option B":"Det fordamper", "Option C":"Det forsvinder for altid", "Option D":"Det bliver til sten", "Correct Option":"B", Explanation:"Ja! Varmen fra Solen omdanner flydende vand til damp — det er fordampning.", Active:true},
    {"Module ID":"LM03", "Step Number":2, Teaching:"Vanddamp stiger op og køler ned højt oppe på himlen og klumper sammen for at danne skyer — det er kondensering.", "Step Image URL":"", Question:"Hvad dannes, når vanddamp køler ned højt på himlen?", "Option A":"Skyer", "Option B":"Sand", "Option C":"Isterninger", "Option D":"Regnbuer", "Correct Option":"A", Explanation:"Korrekt! Afkølet vanddamp klumper sammen og danner skyer.", Active:true},
    {"Module ID":"LM03", "Step Number":3, Teaching:"Når skyer bliver for tunge af vand, falder det tilbage til Jorden som regn — det er nedbør.", "Step Image URL":"", Question:"Hvad kalder vi vand, der falder fra skyer som regn?", "Option A":"Fordampning", "Option B":"Kondensering", "Option C":"Nedbør", "Option D":"Forurening", "Correct Option":"C", Explanation:"Det er rigtigt! Nedbør er vand, der falder tilbage til Jorden som regn, sne eller hagl.", Active:true},
    {"Module ID":"LM04", "Step Number":1, Teaching:"Dine knogler danner en ramme kaldet skelettet, som understøtter og beskytter din krop.", "Step Image URL":"", Question:"Hvad kalder vi rammen af knogler, der understøtter din krop?", "Option A":"Skelettet", "Option B":"Muskel", "Option C":"Hud", "Option D":"Hjerne", "Correct Option":"A", Explanation:"Rigtigt! Dit skelet holder din krop oppe og beskytter organer som dit hjerte.", Active:true},
    {"Module ID":"LM04", "Step Number":2, Teaching:"Dit hjerte pumper blod ud til alle dele af din krop og bærer ilt og næringsstoffer med sig.", "Step Image URL":"", Question:"Hvad er hjertets hovedopgave?", "Option A":"At hjælpe dig med at tænke", "Option B":"At pumpe blod", "Option C":"At fordøje mad", "Option D":"At hjælpe dig med at høre", "Correct Option":"B", Explanation:"Korrekt! Hjertet pumper blod, der fører ilt rundt i hele din krop.", Active:true},
    {"Module ID":"LM04", "Step Number":3, Teaching:"Dine lunger trækker luft ind, så dit blod kan opsamle ilten i den.", "Step Image URL":"", Question:"Hvilken kropsdel hjælper dig med at trække vejret?", "Option A":"Lunger", "Option B":"Lever", "Option C":"Mave", "Option D":"Ører", "Correct Option":"A", Explanation:"Ja! Dine lunger henter ilten fra den luft, du indånder, ind i dit blod.", Active:true},
    {"Module ID":"LM05", "Step Number":1, "Learning Section":"Hvad er en brøk?", Teaching:"En brøk er en måde at vise en del af en helhed på — ligesom én skive af en pizza, der er skåret i lige store stykker.", "Step Image URL":"", Question:"Hvad repræsenterer en brøk?", "Option A":"Et helt tal", "Option B":"En del af en helhed", "Option C":"En slags figur", "Option D":"En vægtenhed", "Correct Option":"B", Explanation:"Korrekt! En brøk beskriver altid en del af noget, der er blevet delt i lige store stykker.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":2, "Learning Section":"Hvad er en brøk?", Teaching:"For at en brøk skal give mening, skal helheden deles i lige store dele — ikke dele af forskellig størrelse.", "Step Image URL":"", Question:"Hvorfor skal delene af en helhed være lige store, når vi taler om brøker?", "Option A":"Så hver del repræsenterer samme mængde", "Option B":"Fordi lige store dele ser pænere ud", "Option C":"Lige store dele er altid større", "Option D":"Det er lige meget, om delene er lige store", "Correct Option":"A", Explanation:"Rigtigt! Hvis delene ikke var lige store, ville brøken ikke beskrive en retfærdig, konsekvent mængde.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":3, "Learning Section":"Hvad er en brøk?", Teaching:"Vi skriver en brøk med to tal adskilt af en streg, som 3/4 — det betyder 3 dele ud af 4 lige store dele.", "Step Image URL":"", Question:"Hvordan skrives en brøk?", "Option A":"To tal adskilt af en streg, som 3/4", "Option B":"Et enkelt tal som 34", "Option C":"Et procenttegn", "Option D":"Kun et decimalkomma", "Correct Option":"A", Explanation:"Ja! Stregen i 3/4 adskiller de to tal, der tilsammen beskriver brøken.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":4, "Learning Section":"Tæller og nævner", Teaching:"Det nederste tal i en brøk kaldes nævneren — det fortæller os, hvor mange lige store dele helheden er delt i.", "Step Image URL":"", Question:"Hvad er nævneren?", "Option A":"Det nederste tal, der viser de samlede lige store dele", "Option B":"Det øverste tal", "Option C":"Stregen i midten", "Option D":"Det hele tal selv", "Correct Option":"A", Explanation:"Korrekt! Nævneren sidder nederst og viser det samlede antal lige store dele.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":5, "Learning Section":"Tæller og nævner", Teaching:"Det øverste tal i en brøk kaldes tælleren — det fortæller os, hvor mange af de lige store dele vi taler om.", "Step Image URL":"", Question:"Hvad er tælleren?", "Option A":"Det nederste tal", "Option B":"Det øverste tal, der viser, hvor mange dele vi har", "Option C":"Helheden", "Option D":"Et symbol", "Correct Option":"B", Explanation:"Rigtigt! Tælleren sidder øverst og tæller, hvor mange af de lige store dele vi mener.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":6, "Learning Section":"Tæller og nævner", Teaching:"I brøken 5/8 er tælleren 5, og nævneren er 8 — det betyder 5 ud af 8 lige store dele.", "Step Image URL":"", Question:"I brøken 5/8, hvad repræsenterer tallet 8?", "Option A":"Tælleren", "Option B":"Nævneren, de samlede lige store dele", "Option C":"Svaret", "Option D":"En rest", "Correct Option":"B", Explanation:"Korrekt! 8-tallet er nævneren — det samlede antal lige store dele, helheden blev delt i.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":7, "Learning Section":"Ækvivalente brøker", Teaching:"Ækvivalente brøker er forskellige brøker, der repræsenterer den samme mængde, som 1/2 og 2/4.", "Step Image URL":"", Question:"Hvad er ækvivalente brøker?", "Option A":"Brøker, der ser ens ud, men betyder noget forskelligt", "Option B":"Forskellige brøker, der repræsenterer den samme mængde", "Option C":"Brøker, der aldrig kan sammenlignes", "Option D":"Kun brøker med samme nævner", "Correct Option":"B", Explanation:"Rigtigt! 1/2 og 2/4 ser forskellige ud, men repræsenterer præcis den samme mængde af en helhed.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":8, "Learning Section":"Ækvivalente brøker", Teaching:"Du kan finde en ækvivalent brøk ved at gange eller dividere både tælleren og nævneren med det samme tal.", "Step Image URL":"", Question:"Hvordan kan du finde en brøk, der er ækvivalent med 2/3?", "Option A":"Gang kun tælleren", "Option B":"Gang både tælleren og nævneren med det samme tal", "Option C":"Læg kun 1 til nævneren", "Option D":"Træk fra tælleren", "Correct Option":"B", Explanation:"Netop! At gange 2/3 med 2/2 giver 4/6, som er ækvivalent.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":9, "Learning Section":"Ækvivalente brøker", Teaching:"Ækvivalente brøker er nyttige, når vi vil sammenligne eller lægge brøker sammen, der ikke har samme nævner.", "Step Image URL":"", Question:"Hvorfor er ækvivalente brøker nyttige?", "Option A":"De hjælper os med at sammenligne eller lægge brøker med forskellig nævner sammen", "Option B":"De får brøker til at forsvinde", "Option C":"De bruges kun i billedkunst", "Option D":"De har ingen reel anvendelse", "Correct Option":"A", Explanation:"Ja! At omskrive brøker til ækvivalenter med samme nævner gør sammenligning og addition meget lettere.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":10, "Learning Section":"Sammenligning af brøker", Teaching:"Når to brøker har samme nævner, er den med den største tæller den største brøk.", "Step Image URL":"", Question:"Hvilken er størst, 3/7 eller 5/7?", "Option A":"3/7", "Option B":"5/7", "Option C":"De er ens", "Option D":"Kan ikke sammenlignes", "Correct Option":"B", Explanation:"Rigtigt! Da begge deler nævneren 7, er brøken med den største tæller, 5/7, størst.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":11, "Learning Section":"Sammenligning af brøker", Teaching:"Når brøker har forskellig nævner, hjælper det at omskrive dem med en fælles nævner, før man sammenligner.", "Step Image URL":"", Question:"Hvad hjælper, når man sammenligner brøker med forskellig nævner?", "Option A":"At ignorere nævnerne", "Option B":"At omskrive dem med en fælles nævner", "Option C":"Altid at vælge den mindste tæller", "Option D":"At lægge tællerne sammen", "Correct Option":"B", Explanation:"Ja! En fælles nævner lader dig sammenligne tællerne direkte og retfærdigt.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":12, "Learning Section":"Sammenligning af brøker", Teaching:"En brøk tæt på 1, som 7/8, repræsenterer næsten en hel, mens en brøk tæt på 0, som 1/8, repræsenterer en meget lille del.", "Step Image URL":"", Question:"Hvilken brøk repræsenterer næsten en hel?", "Option A":"1/8", "Option B":"7/8", "Option C":"0/8", "Option D":"1/2", "Correct Option":"B", Explanation:"Korrekt! 7/8 betyder 7 ud af 8 dele — meget tæt på den fulde helhed.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":13, "Learning Section":"At lægge brøker med samme nævner sammen", Teaching:"For at lægge brøker med samme nævner sammen lægger man bare tællerne sammen og beholder nævneren.", "Step Image URL":"", Question:"Hvordan lægger du 1/5 og 2/5 sammen?", "Option A":"Læg tællerne sammen: 3/5", "Option B":"Læg nævnerne sammen: 1/10", "Option C":"Gang dem: 2/25", "Option D":"Træk dem fra hinanden: 1/5", "Correct Option":"A", Explanation:"Rigtigt! Da nævnerne er ens, lægger du bare 1 + 2 sammen for at få 3/5.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":14, "Learning Section":"At lægge brøker med samme nævner sammen", Teaching:"Hvis sammenlægningen af tællerne giver et tal lig med eller større end nævneren, bliver svaret en hel eller et blandet tal.", "Step Image URL":"", Question:"Hvad er 3/4 + 2/4?", "Option A":"5/4, hvilket er 1 og 1/4", "Option B":"5/8", "Option C":"1/4", "Option D":"6/4 forkortet til 6", "Correct Option":"A", Explanation:"Ja! 3 + 2 = 5, så 5/4 — mere end en hel — er lig med 1 hel og 1/4 til overs.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":15, "Learning Section":"At lægge brøker med samme nævner sammen", Teaching:"At lægge brøker med samme nævner sammen virker på samme måde, uanset hvor mange brøker du lægger sammen.", "Step Image URL":"", Question:"Hvad er 1/6 + 2/6 + 1/6?", "Option A":"4/6", "Option B":"4/18", "Option C":"3/6", "Option D":"1/6", "Correct Option":"A", Explanation:"Korrekt! Læg alle tællerne sammen — 1 + 2 + 1 = 4 — for at få 4/6.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":16, "Learning Section":"At trække brøker med samme nævner fra hinanden", Teaching:"For at trække brøker med samme nævner fra hinanden trækker man tællerne fra hinanden og beholder nævneren.", "Step Image URL":"", Question:"Hvad er 4/9 minus 1/9?", "Option A":"3/9", "Option B":"5/9", "Option C":"4/0", "Option D":"3/18", "Correct Option":"A", Explanation:"Rigtigt! Træk tællerne fra hinanden, 4 − 1 = 3, og behold nævneren 9.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":17, "Learning Section":"At trække brøker med samme nævner fra hinanden", Teaching:"Ligesom ved addition skal nævnerne allerede være ens, før man kan trække to brøker fra hinanden på denne måde.", "Step Image URL":"", Question:"Kan du direkte trække 1/3 fra 1/2 på samme måde?", "Option A":"Nej — nævnerne er forskellige, så de skal gøres ens først", "Option B":"Ja, træk altid tællerne direkte fra hinanden", "Option C":"Nej, brøker kan aldrig trækkes fra hinanden", "Option D":"Ja, bare træk nævnerne fra hinanden", "Correct Option":"A", Explanation:"Korrekt! Med forskellig nævner skal du først finde en fælles nævner, før du trækker fra.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":18, "Learning Section":"At trække brøker med samme nævner fra hinanden", Teaching:"At trække en brøk fra en hel, som 1 minus 3/8, betyder at tænke på helheden som 8/8 først.", "Step Image URL":"", Question:"Hvad er 1 minus 3/8?", "Option A":"5/8", "Option B":"3/8", "Option C":"1/8", "Option D":"4/8", "Correct Option":"A", Explanation:"Ja! Hvis man tænker på 1 som 8/8, giver det 5/8 tilbage at trække 3/8 fra.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":19, "Learning Section":"Brøker i hverdagen", Teaching:"Brøker dukker op overalt i hverdagen — at dele mad, læse opskriftsmål eller fortælle tid, som en halv time.", "Step Image URL":"", Question:"Hvilken af disse er et hverdagseksempel på en brøk?", "Option A":"At dele en halv chokoladeplade med en ven", "Option B":"Kun at tælle hele æbler", "Option C":"At navngive farven på en frugt", "Option D":"At måle temperatur i grader", "Correct Option":"A", Explanation:"Rigtigt! At dele noget i lige store dele, som en halv chokoladeplade, er en brøk i praksis.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":20, "Learning Section":"Brøker i hverdagen", Teaching:"Et ur bruger også brøker — kvart over hel time betyder 1/4 af vejen rundt om urskiven.", "Step Image URL":"", Question:"Hvad betyder \"kvart over\" på et ur?", "Option A":"1/4 af vejen rundt om urskiven", "Option B":"Hele timen er gået", "Option C":"Halvdelen af dagen er ovre", "Option D":"3/4 af timen er tilbage", "Correct Option":"A", Explanation:"Korrekt! Kvart over betyder 15 minutter, hvilket er 1/4 af en 60-minutters time.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM05", "Step Number":21, "Learning Section":"Brøker i hverdagen", Teaching:"Opskrifter bruger ofte brøker til ingredienser, som 3/4 kop mel, så kokke kan måle nøjagtigt den rette mængde.", "Step Image URL":"", Question:"Hvorfor bruger opskrifter ofte brøker?", "Option A":"For at måle ingredienser præcist", "Option B":"For at gøre madlavning sværere", "Option C":"Brøker bruges aldrig i opskrifter", "Option D":"For at undgå at bruge kopper", "Correct Option":"A", Explanation:"Ja! Brøker lader en opskrift beskrive en præcis mængde, som 3/4 kop, i stedet for at gætte.", "Learn More URL":"https://ncert.nic.in/textbook/pdf/fegp107.pdf", "Learn More Label":"Læs NCERT-matematikkapitlet: Brøker", Active:true},
    {"Module ID":"LM06", "Step Number":1, "Learning Section":"Common Nouns", Teaching:"Common nouns name people, places, animals, or things in a general way — not one special, particular one. School, boy, and dog are all common nouns.", "Step Image URL":"", Question:"Which word is a common noun?", "Option A":"Quickly", "Option B":"Pretty", "Option C":"School", "Option D":"Run", "Correct Option":"C", Explanation:"Correct! School names a place in general — that's exactly what a common noun does.", Active:true},
    {"Module ID":"LM06", "Step Number":2, "Learning Section":"Common Nouns", Teaching:"Common nouns can name everyday objects too, like a ball, a book, or a pencil.", "Step Image URL":"", Question:"Which word is a common noun?", "Option A":"Ball", "Option B":"Played", "Option C":"Loudly", "Option D":"Tall", "Correct Option":"A", Explanation:"Right! Ball names a thing — a common noun for any ball, not one special ball.", Active:true},
    {"Module ID":"LM06", "Step Number":3, "Learning Section":"Common Nouns", Teaching:"When you spot a common noun inside a sentence, look for the word that names a person, place, or thing — even with lots of other words around it.", "Step Image URL":"", Question:"Find the common noun: \"The boy kicked the ball happily.\"", "Option A":"kicked", "Option B":"happily", "Option C":"ball", "Option D":"quickly", "Correct Option":"C", Explanation:"Correct! Ball is the thing being named in the sentence — the common noun.", Active:true},
    {"Module ID":"LM06", "Step Number":4, "Learning Section":"Common Nouns", Teaching:"Things you can see and touch around your home — like a chair, a table, or a lamp — are common nouns too.", "Step Image URL":"", Question:"Which word is a common noun?", "Option A":"Quickly", "Option B":"Soft", "Option C":"Sing", "Option D":"Chair", "Correct Option":"D", Explanation:"Yes! Chair names a thing — a common noun.", Active:true},
    {"Module ID":"LM06", "Step Number":5, "Learning Section":"Common Nouns", Teaching:"Jobs people do, like doctor, teacher, or farmer, are common nouns because they describe any person who does that job, not one specific person.", "Step Image URL":"", Question:"Which word is a common noun?", "Option A":"Doctor", "Option B":"Quickly", "Option C":"Happy", "Option D":"Jump", "Correct Option":"A", Explanation:"Right! Doctor names a job that many different people can do — it's a common noun, not the name of one specific person.", Active:true},
    {"Module ID":"LM06", "Step Number":6, "Learning Section":"Common Nouns", Teaching:"You can often complete a sentence with a common noun by thinking of a general thing that fits — like an animal, object, or place.", "Step Image URL":"", Question:"Complete with a common noun: \"I saw a ____ near the pond.\"", "Option A":"Quickly", "Option B":"Duck", "Option C":"Blue", "Option D":"Swimming", "Correct Option":"B", Explanation:"Correct! Duck names an animal — a common noun that fits perfectly near a pond.", Active:true},
    {"Module ID":"LM06", "Step Number":7, "Learning Section":"Common Nouns", Teaching:"Even in a sentence full of action words, there's often a common noun hiding — usually the person, animal, or thing doing the action.", "Step Image URL":"", Question:"Which sentence has a common noun?", "Option A":"She sang sweetly.", "Option B":"He ran fast.", "Option C":"The bird flew away.", "Option D":"They laughed loudly.", "Correct Option":"C", Explanation:"Right! Bird is a common noun — it names an animal in general.", Active:true},
    {"Module ID":"LM06", "Step Number":8, "Learning Section":"Common Nouns", Teaching:"Some words name a place in general — like market, village, or river — while others name one special place. General place names are common nouns.", "Step Image URL":"", Question:"Which word names a place in general (a common noun)?", "Option A":"Delhi", "Option B":"Monday", "Option C":"Quickly", "Option D":"Market", "Correct Option":"D", Explanation:"Yes! Market is a general place name, so it's a common noun — unlike Delhi, which names one particular city.", Active:true},
    {"Module ID":"LM06", "Step Number":9, "Learning Section":"Common Nouns", Teaching:"Everyday school supplies — like a pencil, eraser, or bag — are common nouns because they name things in general.", "Step Image URL":"", Question:"Which of these is a common noun?", "Option A":"Pencil", "Option B":"Carefully", "Option C":"Bright", "Option D":"Jumped", "Correct Option":"A", Explanation:"Correct! Pencil names a thing — a common noun.", Active:true},
    {"Module ID":"LM06", "Step Number":10, "Learning Section":"Common Nouns", Teaching:"A word like teacher names any person who does that job — it's a common noun. A word like Raju names one particular person — that's a proper noun, coming up next.", "Step Image URL":"", Question:"Which word names any person doing a job (a common noun)?", "Option A":"Raju", "Option B":"Teacher", "Option C":"Monday", "Option D":"Delhi", "Correct Option":"B", Explanation:"Right! Teacher names any person doing that job — a common noun.", Active:true},
    {"Module ID":"LM06", "Step Number":11, "Learning Section":"Proper Nouns", Teaching:"Proper nouns name one specific person, place, or thing — and they always start with a capital letter. Ganga is the name of one particular river.", "Step Image URL":"", Question:"Which word is a proper noun?", "Option A":"mountain", "Option B":"river", "Option C":"city", "Option D":"Ganga", "Correct Option":"D", Explanation:"Correct! Ganga names one particular river — a proper noun.", Active:true},
    {"Module ID":"LM06", "Step Number":12, "Learning Section":"Proper Nouns", Teaching:"What makes a word a proper noun isn't just its capital letter — it's that the word names one particular, special thing instead of a general category.", "Step Image URL":"", Question:"Why is \"Delhi\" a proper noun?", "Option A":"It names one particular city.", "Option B":"It is a place.", "Option C":"It starts with a capital by chance.", "Option D":"It is a long word.", "Correct Option":"A", Explanation:"Right! Delhi is a proper noun because it names one particular city, not cities in general.", Active:true},
    {"Module ID":"LM06", "Step Number":13, "Learning Section":"Proper Nouns", Teaching:"Every common noun can be matched with an example that's a proper noun — like boy (common) and Ramesh (proper), one specific boy.", "Step Image URL":"", Question:"Which pair matches a common noun with its proper noun?", "Option A":"school – Monday", "Option B":"river – fast", "Option C":"boy – Ramesh", "Option D":"dog – bark", "Correct Option":"C", Explanation:"Yes! Ramesh is the specific name for a boy — pairing a common noun with its proper noun.", Active:true},
    {"Module ID":"LM06", "Step Number":14, "Learning Section":"Proper Nouns", Teaching:"Festivals like Diwali, Holi, and Eid are proper nouns because each one names one particular, special celebration.", "Step Image URL":"", Question:"Choose the proper noun: \"We celebrate Diwali every year.\"", "Option A":"celebrate", "Option B":"every", "Option C":"year", "Option D":"Diwali", "Correct Option":"D", Explanation:"Correct! Diwali names a specific festival — a proper noun.", Active:true},
    {"Module ID":"LM06", "Step Number":15, "Learning Section":"Proper Nouns", Teaching:"Country names, like India, are always proper nouns because each one names a single, specific country.", "Step Image URL":"", Question:"Which word must start with a capital letter as a proper noun?", "Option A":"teacher", "Option B":"festival", "Option C":"India", "Option D":"country", "Correct Option":"C", Explanation:"Right! India is a specific country, so it's a proper noun and must be capitalised.", Active:true},
    {"Module ID":"LM06", "Step Number":16, "Learning Section":"Proper Nouns", Teaching:"Because proper nouns name something specific, they must always start with a capital letter — even in the middle of a sentence.", "Step Image URL":"", Question:"Which sentence uses a proper noun correctly?", "Option A":"We live in mumbai.", "Option B":"We live in a city.", "Option C":"We live in a Mumbai.", "Option D":"We live in Mumbai.", "Correct Option":"D", Explanation:"Yes! Mumbai is a specific city, so it needs a capital letter — that's the only option that gets it right.", Active:true},
    {"Module ID":"LM06", "Step Number":17, "Learning Section":"Proper Nouns", Teaching:"When a sentence mentions someone's name — like Meena, Ravi, or Asha — that name is a proper noun, even surrounded by ordinary words.", "Step Image URL":"", Question:"Spot the proper noun: \"My friend Meena loves to read story books.\"", "Option A":"Meena", "Option B":"friend", "Option C":"loves", "Option D":"books", "Correct Option":"A", Explanation:"Correct! Meena is the friend's specific name — a proper noun.", Active:true},
    {"Module ID":"LM06", "Step Number":18, "Learning Section":"Proper Nouns", Teaching:"Days of the week, like Monday, are proper nouns because each one names one specific day — but words for general time periods, like holiday, are common nouns.", "Step Image URL":"", Question:"Which of these is NOT a proper noun?", "Option A":"Monday", "Option B":"holiday", "Option C":"December", "Option D":"Asia", "Correct Option":"B", Explanation:"Right! Holiday is general — it doesn't name one specific day — so it's the one that is NOT a proper noun here.", Active:true},
    {"Module ID":"LM06", "Step Number":19, "Learning Section":"Proper Nouns", Teaching:"A single sentence can contain more than one proper noun — count carefully for the names of specific people and places.", "Step Image URL":"", Question:"\"Ravi visited the Taj Mahal last summer.\" How many proper nouns?", "Option A":"1", "Option B":"2", "Option C":"3", "Option D":"4", "Correct Option":"B", Explanation:"Correct! Ravi and Taj Mahal are both proper nouns — that's two.", Active:true},
    {"Module ID":"LM06", "Step Number":20, "Learning Section":"Proper Nouns", Teaching:"The capital letter on a proper noun is a signal to the reader: this word names something specific and special, not just any example of its kind.", "Step Image URL":"", Question:"Why do proper nouns always start with a capital letter?", "Option A":"They are long words.", "Option B":"They are hard to spell.", "Option C":"They name something specific and special.", "Option D":"They start sentences.", "Correct Option":"C", Explanation:"Yes! Proper nouns name something specific and special — that capital letter is a clue.", Active:true},
    {"Module ID":"LM06", "Step Number":21, "Learning Section":"Collective Nouns", Teaching:"Collective nouns name a whole group of people or animals as one unit. Different animals get their own special group names — a flock for sheep, a herd for cows.", "Step Image URL":"", Question:"Correct collective noun for a group of sheep?", "Option A":"Herd", "Option B":"Flock", "Option C":"Swarm", "Option D":"Pack", "Correct Option":"B", Explanation:"Right! A group of sheep is a flock.", Active:true},
    {"Module ID":"LM06", "Step Number":22, "Learning Section":"Collective Nouns", Teaching:"Groups of people working or playing together also get their own collective noun, like a team of players or a class of students.", "Step Image URL":"", Question:"Correct collective noun for a group of players?", "Option A":"Family", "Option B":"Library", "Option C":"Team", "Option D":"Class", "Correct Option":"C", Explanation:"Correct! A group of players is a team.", Active:true},
    {"Module ID":"LM06", "Step Number":23, "Learning Section":"Collective Nouns", Teaching:"A swarm is the special collective noun used for a buzzing group of insects, like bees.", "Step Image URL":"", Question:"\"A ____ of bees flew over the garden.\"", "Option A":"herd", "Option B":"swarm", "Option C":"flock", "Option D":"team", "Correct Option":"B", Explanation:"Yes! A group of bees is a swarm.", Active:true},
    {"Module ID":"LM06", "Step Number":24, "Learning Section":"Collective Nouns", Teaching:"Soldiers marching together as a group are called an army — that's their collective noun.", "Step Image URL":"", Question:"Correct collective noun for a group of soldiers?", "Option A":"Army", "Option B":"Class", "Option C":"Bunch", "Option D":"Fleet", "Correct Option":"A", Explanation:"Correct! A group of soldiers is an army.", Active:true},
    {"Module ID":"LM06", "Step Number":25, "Learning Section":"Collective Nouns", Teaching:"A group of students sitting together to learn is simply called a class.", "Step Image URL":"", Question:"\"A ____ of students stood up to sing.\"", "Option A":"herd", "Option B":"swarm", "Option C":"class", "Option D":"pack", "Correct Option":"C", Explanation:"Right! A group of students is a class.", Active:true},
    {"Module ID":"LM06", "Step Number":26, "Learning Section":"Collective Nouns", Teaching:"Matching the right collective noun to the right animal matters — cows are described as a herd, not a flock or a swarm.", "Step Image URL":"", Question:"Which sentence uses a collective noun correctly?", "Option A":"A flock of cows grazed.", "Option B":"A swarm of cows grazed.", "Option C":"A team of cows grazed.", "Option D":"A herd of cows grazed.", "Correct Option":"D", Explanation:"Correct! Cows are described as a herd.", Active:true},
    {"Module ID":"LM06", "Step Number":27, "Learning Section":"Collective Nouns", Teaching:"Ships travelling together are called a fleet — a collective noun just for vehicles like ships and boats.", "Step Image URL":"", Question:"Correct collective noun for a group of ships?", "Option A":"Army", "Option B":"Pack", "Option C":"Fleet", "Option D":"Bunch", "Correct Option":"C", Explanation:"Right! A group of ships is a fleet.", Active:true},
    {"Module ID":"LM06", "Step Number":28, "Learning Section":"Collective Nouns", Teaching:"Not every collective noun is for living things — small objects that are grouped together can have one too, like a bunch of keys.", "Step Image URL":"", Question:"Collective noun for \"a group of keys\"?", "Option A":"Bunch", "Option B":"Herd", "Option C":"Flock", "Option D":"Team", "Correct Option":"A", Explanation:"Yes! A group of keys is a bunch.", Active:true},
    {"Module ID":"LM06", "Step Number":29, "Learning Section":"Collective Nouns", Teaching:"A collection is the word used when many similar objects, like books, are gathered together.", "Step Image URL":"", Question:"The librarian arranged the new ____ of books.", "Option A":"herd", "Option B":"flock", "Option C":"swarm", "Option D":"collection", "Correct Option":"D", Explanation:"Correct! Books grouped together are called a collection.", Active:true},
    {"Module ID":"LM06", "Step Number":30, "Learning Section":"Collective Nouns", Teaching:"Birds flying together as a group are called a flock — just like sheep.", "Step Image URL":"", Question:"Which sentence correctly uses a collective noun?", "Option A":"A swarm of birds flew south.", "Option B":"A flock of birds flew south.", "Option C":"A herd of birds flew south.", "Option D":"A team of birds flew south.", "Correct Option":"B", Explanation:"Right! Birds are described as a flock.", Active:true},
    {"Module ID":"LM06", "Step Number":31, "Learning Section":"Abstract Nouns", Teaching:"Abstract nouns name feelings, ideas, or qualities — things you can't see or touch, but can definitely feel. Happiness is a feeling, so it's an abstract noun.", "Step Image URL":"", Question:"Which word is an abstract noun?", "Option A":"Table", "Option B":"Flower", "Option C":"Garden", "Option D":"Happiness", "Correct Option":"D", Explanation:"Correct! Happiness is a feeling — an abstract noun.", Active:true},
    {"Module ID":"LM06", "Step Number":32, "Learning Section":"Abstract Nouns", Teaching:"A quality like honesty can't be picked up or touched — it's something you notice in how a person acts, which makes it an abstract noun.", "Step Image URL":"", Question:"Which names a quality you cannot touch (abstract)?", "Option A":"Honesty", "Option B":"Book", "Option C":"Pencil", "Option D":"Chair", "Correct Option":"A", Explanation:"Right! Honesty is a quality, untouchable — an abstract noun.", Active:true},
    {"Module ID":"LM06", "Step Number":33, "Learning Section":"Abstract Nouns", Teaching:"When a sentence describes a quality someone shows — like kindness — that quality word is the abstract noun in the sentence.", "Step Image URL":"", Question:"\"Her kindness made everyone smile.\" Which word is the abstract noun?", "Option A":"smile", "Option B":"everyone", "Option C":"kindness", "Option D":"made", "Correct Option":"C", Explanation:"Correct! Kindness is the quality being described.", Active:true},
    {"Module ID":"LM06", "Step Number":34, "Learning Section":"Abstract Nouns", Teaching:"Concrete nouns name things you can touch, like a table. Abstract nouns name things you can't touch, like courage. Spotting the difference helps you sort nouns quickly.", "Step Image URL":"", Question:"Which pair has one concrete and one abstract noun?", "Option A":"table – courage", "Option B":"dog – cat", "Option C":"ball – chair", "Option D":"river – mountain", "Correct Option":"A", Explanation:"Yes! Table is concrete, while courage is abstract — that's the matching pair.", Active:true},
    {"Module ID":"LM06", "Step Number":35, "Learning Section":"Abstract Nouns", Teaching:"Friendship is a feeling shared between people — you can't hold it in your hand, which is exactly what makes it an abstract noun.", "Step Image URL":"", Question:"Which word is an abstract noun?", "Option A":"Mango", "Option B":"Window", "Option C":"Friendship", "Option D":"School", "Correct Option":"C", Explanation:"Correct! Friendship is a feeling, or idea — an abstract noun.", Active:true},
    {"Module ID":"LM06", "Step Number":36, "Learning Section":"Abstract Nouns", Teaching:"Strong feelings like anger are abstract nouns because they describe something you experience inside, not something you can hold.", "Step Image URL":"", Question:"Which of these words is an abstract noun?", "Option A":"Garden", "Option B":"Anger", "Option C":"River", "Option D":"Mango", "Correct Option":"B", Explanation:"Right! Anger is a feeling — an abstract noun.", Active:true},
    {"Module ID":"LM06", "Step Number":37, "Learning Section":"Abstract Nouns", Teaching:"Look for the word that names a quality someone shows, rather than a person, animal, or object — that word is the abstract noun in the sentence.", "Step Image URL":"", Question:"Which sentence has an abstract noun?", "Option A":"The cat sat on the mat.", "Option B":"Her honesty surprised the teacher.", "Option C":"He bought a new bicycle.", "Option D":"The flowers bloomed.", "Correct Option":"B", Explanation:"Correct! Honesty is the quality named in this sentence.", Active:true},
    {"Module ID":"LM06", "Step Number":38, "Learning Section":"Abstract Nouns", Teaching:"Joy, like happiness and anger, is something you feel deep inside — not something you can pick up, which makes it abstract.", "Step Image URL":"", Question:"Which names something you feel but can't touch?", "Option A":"Table", "Option B":"Pencil", "Option C":"Joy", "Option D":"Chair", "Correct Option":"C", Explanation:"Yes! Joy is felt, not touched — an abstract noun.", Active:true},
    {"Module ID":"LM06", "Step Number":39, "Learning Section":"Abstract Nouns", Teaching:"When soldiers are described as brave, the quality they show — courage — is the abstract noun in that sentence.", "Step Image URL":"", Question:"\"The soldiers showed great courage in battle.\" Which word is the abstract noun?", "Option A":"soldiers", "Option B":"battle", "Option C":"showed", "Option D":"courage", "Correct Option":"D", Explanation:"Correct! Courage is the quality named in the sentence.", Active:true},
    {"Module ID":"LM06", "Step Number":40, "Learning Section":"Abstract Nouns", Teaching:"Peace is an idea or feeling of calm — you can't touch it, but you can definitely sense it, which makes it an abstract noun.", "Step Image URL":"", Question:"Which word is an abstract noun?", "Option A":"Apple", "Option B":"Mountain", "Option C":"Bicycle", "Option D":"Peace", "Correct Option":"D", Explanation:"Right! Peace is an idea or feeling — an abstract noun.", Active:true},
    {"Module ID":"LM06", "Step Number":41, "Learning Section":"Mixed Practice", Teaching:"Now let's mix all four types together! In a sentence with several nouns, look closely at each one — is it general, specific, a group, or a feeling?", "Step Image URL":"", Question:"\"Rahul joined a team of young scientists.\" Which word is a proper noun?", "Option A":"team", "Option B":"scientists", "Option C":"Rahul", "Option D":"young", "Correct Option":"C", Explanation:"Correct! Rahul is a specific person's name — a proper noun.", Active:true},
    {"Module ID":"LM06", "Step Number":42, "Learning Section":"Mixed Practice", Teaching:"Remember: a collective noun names a whole group acting as one unit — like a committee making a decision together.", "Step Image URL":"", Question:"\"The committee discussed the project's success.\" Which word is a collective noun?", "Option A":"committee", "Option B":"project", "Option C":"success", "Option D":"discussed", "Correct Option":"A", Explanation:"Right! Committee names a group.", Active:true},
    {"Module ID":"LM06", "Step Number":43, "Learning Section":"Mixed Practice", Teaching:"Even in a sentence about a whole village, the abstract noun is still the feeling or quality being described — not the people or place.", "Step Image URL":"", Question:"\"Her courage helped the whole village.\" Which word is an abstract noun?", "Option A":"village", "Option B":"helped", "Option C":"whole", "Option D":"courage", "Correct Option":"D", Explanation:"Correct! Courage is the quality named.", Active:true},
    {"Module ID":"LM06", "Step Number":44, "Learning Section":"Mixed Practice", Teaching:"To sort a common noun from the rest, ask: does this word name something general, rather than one specific thing, group, or feeling?", "Step Image URL":"", Question:"Which word in this list is a common noun?", "Option A":"Friendship", "Option B":"Asia", "Option C":"river", "Option D":"Monday", "Correct Option":"C", Explanation:"Yes! River is a general name — a common noun.", Active:true},
    {"Module ID":"LM06", "Step Number":45, "Learning Section":"Mixed Practice", Teaching:"A sentence can hold more than one type of noun at once. Identify each noun's job separately — which one is the group, and which one is the specific name?", "Step Image URL":"", Question:"\"The class cheered when Priya scored a goal.\" Identify the collective noun and proper noun.", "Option A":"cheered (collective), goal (proper)", "Option B":"class (collective), Priya (proper)", "Option C":"goal (collective), class (proper)", "Option D":"Priya (collective), class (proper)", "Correct Option":"B", Explanation:"Correct! Class is the group (collective noun), and Priya is the specific name (proper noun).", Active:true},
    {"Module ID":"LM06", "Step Number":46, "Learning Section":"Mixed Practice", Teaching:"Scan each sentence for a word that names a feeling or quality, rather than a person, place, group, or object.", "Step Image URL":"", Question:"Which sentence contains an abstract noun?", "Option A":"The army marched into the town.", "Option B":"Honesty is the best policy.", "Option C":"The herd crossed the river.", "Option D":"Meena bought a new bicycle.", "Correct Option":"B", Explanation:"Right! Honesty is the abstract noun here.", Active:true},
    {"Module ID":"LM06", "Step Number":47, "Learning Section":"Mixed Practice", Teaching:"Don't let a proper noun like a place name distract you from spotting the collective noun in the same sentence.", "Step Image URL":"", Question:"\"A swarm of bees frightened Rohan near Juhu beach.\" Which word is a collective noun?", "Option A":"swarm", "Option B":"Rohan", "Option C":"Juhu", "Option D":"bees", "Correct Option":"A", Explanation:"Correct! Swarm names the group of bees.", Active:true},
    {"Module ID":"LM06", "Step Number":48, "Learning Section":"Mixed Practice", Teaching:"When sorting a list of nouns by type, look for the one word that's capitalised because it names something one-of-a-kind.", "Step Image URL":"", Question:"Sort by type: kindness, Mumbai, herd, pencil. Which is a proper noun?", "Option A":"kindness", "Option B":"herd", "Option C":"Mumbai", "Option D":"pencil", "Correct Option":"C", Explanation:"Yes! Mumbai is one particular city — a proper noun.", Active:true},
    {"Module ID":"LM06", "Step Number":49, "Learning Section":"Mixed Practice", Teaching:"A sentence celebrating a group's win often contains both a collective noun for the group and an abstract noun for how everyone feels.", "Step Image URL":"", Question:"\"The team's victory filled the players with joy.\" Which word is a collective noun?", "Option A":"team", "Option B":"players", "Option C":"victory", "Option D":"joy", "Correct Option":"A", Explanation:"Correct! Team names the group of players.", Active:true},
    {"Module ID":"LM06", "Step Number":50, "Learning Section":"Mixed Practice", Teaching:"For the final challenge, sort every noun type in one sentence at once: who is named specifically, what feeling is described, and what group is mentioned?", "Step Image URL":"", Question:"\"Anjali's kindness inspired the whole class in Pune.\" Which option correctly labels the nouns?", "Option A":"Anjali (common), kindness (proper), class (abstract), Pune (collective)", "Option B":"Anjali (collective), kindness (common), class (proper), Pune (abstract)", "Option C":"Anjali (abstract), kindness (proper), class (common), Pune (collective)", "Option D":"Anjali (proper), kindness (abstract), class (collective), Pune (proper)", "Correct Option":"D", Explanation:"Excellent! Anjali and Pune are proper nouns (specific names), kindness is abstract (a quality), and class is collective (a group) — you've mastered all four noun types!", Active:true}
];

export { QUIZ_LEARNING_MODULES_DA, QUIZ_LEARNING_STEPS_DA };

// Danish mirror of FALLBACK.assignmentSubjects in pages/portal.js. The
// `Subject` value here MUST exactly match the (translated) `Subject` field
// used on QUIZ_LEARNING_MODULES_DA entries above, since portal.js joins
// topics to a subject card via `m.Subject === subjectName`. English Grammar
// is intentionally left as 'English Grammar' (matching its untranslated
// modules) rather than a Danish name, for the same reason its quiz content
// stays in English — see the file header comment above.
//
// 'Social Studies', 'General Knowledge', and 'Artificial Intelligence' have
// no hardcoded English FALLBACK content either (their topics/questions live
// entirely in the live Google Sheet, fetched in English). Their Danish cards
// are included here for consistency with the English subject list, but —
// exactly like the existing English-only behaviour when the Sheet is
// unreachable — they will show the portal's existing "No learning topics
// yet" empty state in Danish until/unless a teacher adds Danish rows for
// them. This is not a regression: the same empty state already exists for
// these subjects in English today.
const QUIZ_ASSIGNMENT_SUBJECTS_DA = [
  { Subject: 'English Grammar',  SubjectEN: 'English Grammar',  Tagline: 'Grammatik, ordforråd og skrivefærdigheder', 'Icon (FontAwesome solid)': 'fa-spell-check', Emoji: '📚', 'Color (Hex)': '#3b82f6', 'Display Order': 1, Active: true },
  { Subject: 'Matematik',        SubjectEN: 'Mathematics',      Tagline: 'Tal, former og problemløsning',              'Icon (FontAwesome solid)': 'fa-calculator',  Emoji: '➗', 'Color (Hex)': '#f97316', 'Display Order': 2, Active: true },
  { Subject: 'Naturfag',         SubjectEN: 'Science',          Tagline: 'Planter, kroppen og hvordan verden fungerer','Icon (FontAwesome solid)': 'fa-flask',       Emoji: '🔬', 'Color (Hex)': '#22c55e', 'Display Order': 3, Active: true },
  { Subject: 'Samfundsfag',      SubjectEN: 'Social Studies',   Tagline: 'Historie, geografi og verden omkring os',    'Icon (FontAwesome solid)': 'fa-earth-asia',  Emoji: '🌍', 'Color (Hex)': '#eab308', 'Display Order': 4, Active: true },
  { Subject: 'Almen Viden',      SubjectEN: 'General Knowledge',Tagline: 'Sjove fakta og almen viden',                 'Icon (FontAwesome solid)': 'fa-lightbulb',   Emoji: '💡', 'Color (Hex)': '#a855f7', 'Display Order': 5, Active: true },
];

export { QUIZ_ASSIGNMENT_SUBJECTS_DA };
